### ISSUE TITLE
V2 controller not recognised

### ISSUE THREAD

**Issue by DVLP** [Jays2Kings/DS4Windows#183] opened 2016-10-06 11:08 UTC
I'm successfully using DS4 controller with DS4Windows and it's awesome, so I bought another controller for split screen games. Unlike the first one the now controller is **V2**. It's connected to my system through bluetooth just like the first one but it's not being recognised by DS4Windows :/

**Comment by cassava** [comment] 2016-10-06 11:47
Possibly duplicate of #177.

**Comment by TristanYoung** [comment] 2016-10-06 21:53
Definitely a duplicate.  I'm testing an updated version of DS4Windows with the PID for the new controllers added.  So far, seems to be working.

**Comment by DVLP** [comment] 2016-10-07 11:01
Yeah so I made a duplicate, close please

**Closed as completed** 2016-10-09 03:28 UTC
